sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8
  - 6
  - 4
os:
  - linux
  - osx
env:
  - BUILD_LEADER_ID=7
jobs:
  include:
    - stage: release
      node_js: 8
      os: linux
      after_success:
        - yarn semantic-release
        - bash yarn.sh
install:
  - yarn install --ignore-engines
before_script:
  - yarn lint
script:
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
