language: node_js
deploy:
  provider: npm
  email: csaba.tuncsik@gmail.com
  api_key:
    secure: OgRfLbU6o68KNKheIk+HQyCvJCcrUVYo696sRb2krnelNrO7KzcAyYqykb2rXQjOlOcnxiRe9wETbq6/KxGJch4yMtXhKp/6OUThhTofHBXLxYgYC9OFDT5EP36iXpDDI0M6b3BR5uuwJzHX4/A4kOR+f389Q5s/JxwcaCbA1e0=
  on:
    tags: true
    all_branches: true
    repo: cstuncsik/gulp-teddy
